baseURL = "https://pacodiazdg.github.io/"
languageCode = "es-es"
title = 'pacodiazdg.github.io'
theme = "hugo-theme-stack"
pagination.pagerSize = 5
enableEmoji = true
[params]
  mainSections = ["posts"]
  featuredImageField = "image"
  rssFullContent = true
  favicon = "/favicon.ico"
  [params.dateFormat]
        published = "2 January 2006"
        lastUpdated = "2 January 2006"

  [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
  [params.sidebar]
        emoji = "🗿"
        local = false
        subtitle = "Blog de programación, electrónica y GNU/Linux."
    [params.sidebar.avatar]
    enabled = true
    local = false
    src = "https://avatars.githubusercontent.com/u/26071783?v=4"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "Github"
    name = "Github"
    url = "https://github.com/PacodiazDG"
    weight = 2
  [[menu.main]]
    identifier = "Linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/francisco-javier-d-a463901a2/"
    weight = 2