baseURL = "https://PacodiazDG.github.io/"
languageCode = "es-es"
title = 'pacodiazdg.github.io'
theme = 're-terminal'
pagination.pagerSize = 5












[params]
  # ["orange", "blue", "red", "green", "pink", "paper"]
  themeColor = "green"

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

[languages]
    [languages.en.params.logo]
      logoText = "PacodiazDG"
      logoHomeLink = "/"
